services:
  exp-tg-bot:
    build: .
    image: alex3iii/exp-tg-bot:latest
    container_name: exp-tg-bot-inst
    restart: unless-stopped
    environment:
      EXPBOT_BOT_TOKEN: ${EXPBOT_BOT_TOKEN}
      EXPBOT_DB_FILE_PATH: /data/expenses.db
    volumes:
      - exp-tg-bot-data:/data

volumes:
  exp-tg-bot-data:
